#import "@preview/charged-ieee:0.1.4": ieee

#show: ieee.with(
  title: [Investigating Basin Hopping and Minima Hopping Combinations and Modifications ],
  abstract: [

  ],
  authors: (
    (
      name: "Arham Rajendra Lodha",
      department: [Department of Mathematics],
      organization: [University of Texas at Austin],
      location: [Austin, Texas],
      email: "arhamsmita@gmail.com",
    ),
    // (
    //   name: "Laurenz Mädje",
    //   department: [Co-Founder],
    //   organization: [Typst GmbH],
    //   location: [Berlin, Germany],
    //   email: "maedje@typst.app",
    // ),
  ),
  index-terms: (),
  bibliography: bibliography("refs.bib", full: true, style: "american-chemical-society"),
)

#let LJ(N) = $"LJ"_(#N)$

#hide[@hoare1971advphys@hoare1971natureps@hoare1972natureps@hoare1975advphys@hoare1979advchemphys@freeman1985jcp@farges1985ss@wille1987cpl@northby1987jcp@coleman1994jgo@xue1994jgo@pillardy1995jpc@doye1995jcp@doye1995cpl]

= Introduction

// TODO ADD ALL REFERENCES HERE
Lennard Jones (LJ) clusters are one such test system. The total potential energy for a $N$ atom system $LJ_(N)$, $V$, is calculated as a sum over all pairs of atoms: $ V =4 epsilon sum_(i = 0)^(n - 1)sum_(j = i + 1)^(n)[
  ((sigma)/(r_(i j)))^(12) - ((sigma)/(r_(i j)))^(6)
] $ where $epsilon$ is the depth of the pair equilibrium potential well and $2^(1 slash 6)sigma$ is the pair equilibrium separation distance. For the purposes of this study we will use reduced units thus $epsilon = sigma = 1$. The initial interest in LJ clusters were motivated by the desire to study the nucleation rate of noble gases. As a result, a wealth of empirical data was generated. Through the combined effort of a many individuals, likely candidates for the global minima of $LJ(10)$ clusters has been found up to $N = 147$#super([[1-14]]). Previous studies revealed the Mackay Icosehedron as the structural motif seen in the global minima of the LJ clusters in the size range of $10 - 150$ atoms. Complete icosahedra can be found at $N = 13, 55, 147, #sym.dots.h$

However, for a number of cluster sizes, the global minima are not based on icosahedral structures. In these cases, locating the lowest-energy configuration is significantly more challenging, as the global minima of free energy and potential energy coincide only at temperatures far below the melting point—where relaxation dynamics become extremely slow. Moreover the geometry of the PES can play a big role in determining the ease of global optimization.

= Methods
Basin Hopping (BH) and Minimum Hopping (MH) are similarly constructed. They both have a trial move that displaces the atoms in the system from the current local minimum to a new state and locally optimizes the new state to generate a candidate configuration. Then, the methods apply an acceptance criteria to determine if the candidate configuration is accepted or rejected. MH adds a history aspect that compares the candidate configuration to all previously found local minima to discourage repeated visits to the same local minimum. On the other hand, standard BH only keeps track of the currents local minimum. However, BH can be modified to include history. After the acceptance criteria, an optional jump can occur to cross high energy barriers. This section will investigate BH, MH, and their modification by the categories of trial move, acceptance criteria, history, and jumping. A total of 36 configurations were tested for each cluster. Dividing the algorithms into these categories will allow us to combine features from different algorithms and select one from each category. GO simulations using a combinations of the BH and MH methodology will be explored to determine which features of the combined algorithm will successfully and efficiently predict the global minimum of a chemical system and how a chemical systems PES can affect the optimal parameters. We will also discuss the specifics of the computational protocol used to define the simulations and evaluate the performance of the algorithms.

== Trial Move
=== Basin Hopping
In the Basin Hopping algorithm, a trial move is generated by perturbing the current local minimum $X_i$ using a random displacement. The most common approach employs a uniform distribution:
$ X_(i + 1) & = X_(i) + dif r * delta "where" delta ~ U([-1, 1]) $

Here, $dif r$ controls the step size of the perturbation. After generating the candidate configuration $X_(i+1)$, a local optimization step is applied to relax it to the nearest local minimum of the potential energy surface.

=== Minimum Hopping
The MH trial move runs a series of MD simulations initiated from the current local minimum $X_(i)$. The simulation uses a with time step of $0.1$ fs and starts with the atomic velocities sampled from the Boltzmann distribution corresponding to a prescribed kinetic energy $E_("kinetic")$. The energy is chosen so the system can overcome energy barriers lower than $E_("kinetic")$ measured relative to current local minimum @Goedecker.

The MD trajectory is integrated until the potential energy has traversed the $m d m i n$ local maxima and settled into the $m d m i n$-th minimum @Goedecker. At this point, the geometry is relaxed using local optimization to obtain a precise minimum M.

The kinetic energy for the next trial is then adaptively adjusted based on whether $M$ represents a previously encountered structure:
1. If $M$ is a new local minimum, $E_("kinetic")$ is reduced by a factor $beta = 0.96$
2. If $M$ coincides with $X_(i)$ or any previously visited minimum, $E_("kinetic")$ is increased by a factor of $beta = 1.04$.

This cycle of MD propagation, local optimization, and energy rescaling continues until a geometry is found that is distinct from all geometries in the history. The unique configuration becomes the next iterate $X_(i + 1)$.

== Acceptance Criteria
=== Basin Hopping
In BH, the acceptance criterion follows the Metropolis scheme used in canonical Monte Carlo simulations. After the trial move displaces the system from configuration $X_(i)$ to $X_(i + 1)$, and $X_(i + 1)$ is relaxed to the nearest local minimum, the potential energy $V$ is evaluated at both geometries.

- If $V(X_(i + 1)) < V(X_(i))$, the move is always accepted and the current configuration is updated to $X_(i + 1)$ @Wales.
- If $V(X_(i + 1)) >= V_(X_(i))$, the move is accepted with probability $ PP_("Accepted") = exp((V(X_(i)) - V(X_(i + 1)))/(kappa_(B) T)). $ This is implemented by comparing $PP_("Accepted")$ to a uniformly sampled random number $r in [0, 1]$. The move is accepted if $ exp((V(X_(i)) - V(X_(i + 1)))/(kappa_(B) T)) > r. $<Basinhoppingacceptance> Otherwise, the system stays at $X_(i)$.

=== Minima Hopping
In MH, acceptance is governed by an energy window defined by a dynamically adjusted parameter $E_("diff")$. A new geometry is accepted if its potential energy satisfies $ V(X_(i + 1)) < V(X_(i)) + E_("diff"). $ This allows the algorithm to escape shallow local minima while still favoring lower-energy configurations. The parameter $E_("diff")$ is dynamically adjusted during the simulation using a multiplicative factor $alpha$:
$ E_("diff") dot alpha -> E_("diff") $
- If the move $X_(i + 1)$ is rejected, $alpha = 1.02$. Increasing $E_("diff")$ encourages exploration.
- If the move $X_(i)$ is accepted, $alpha = 0.98$. Decreasing $E_("diff")$ wants to promote convergence toward low-energy regions.
This adaptive mechanism ensures that the algorithm efficiently explores the energy landscape without getting trapped in high-energy basins.

== History
=== History Weighting (+hw)
We modify the BH algorithm by adding a history dependent term into the acceptance criterion. This modification encourages the system to escape from regions it has frequently visited in the past, thus promoting exploration of uncharted areas of the PES @Rossi_2009. This adjustment modifies inequality @Basinhoppingacceptance by introducing two key components:

1. A history function, $h(Y, n)$, which is the relative frequency of visits to configuration $Y$ up to the $n$th trial move.
2. A weight factor, $w$, that controls the influence that the history term has on the acceptance probability.

Our implementation of the history function differs slightly from Rossi and Ferrando's HISTO algorithm @Rossi_2009. Rather than using common neighbor analysis to group structures into types, we construct a histogram of unique local minima encountered during the search. We define the history function as follows:

$ h(Y, n) := (\#{X_(m) = Y mid(|) n in {1, #sym.dots.h, n}})/(n). $

The history function is updated as follows:

1. If $X_(i + 1)$ is accepted, then $h(X_(i + 1), n + 1)$ is incremented by $(1)/(n + 1)$
2. If $X_(i + 1)$ is rejected, then $h(X_(i), n + 1)$ is incremented by $(1)/(n +1)$

The modified acceptance criteria becomes:

$ exp((V(X_(i)) - V(X_(i + 1)) + w[h(X_(i) - h(X_(i+1)))])/(kappa_(B) T)) > r $
This formulation biases the algorithm against revisiting high-frequency minima, effectively guiding the search toward novel regions of configuration space.

=== Minimum Hopping (+mh)
The MH algorithm comes with a history by design. During each trial move, MH systematically checks whether the proposed geometry has been previously accepted into the history list. The trial move continues—generating new displacements and performing local optimizations—until it produces a novel minimum that does not already exist in the history.

This built-in history mechanism is highly flexible: it is not limited to molecular dynamics (MD) displacements. For instance, MH can be seamlessly combined with the uniform random displacement used in standard BH. In this hybrid approach, MH would repeatedly apply the displacement from Equation (1), followed by local optimization, until a configuration not yet stored in the history is found.

=== No History (-h)
We also have the option to opt for no history. Disabling the history comparison removes the requirement to check if $X_(i + 1)$ against all previously accepted geometries. Instead, the algorithm compares the current state $X_(i)$ and the candidate configuration $X_(i + 1)$. In this mode, kinetic energy is added only when $V(X_(i + 1)) = V(x_(i))$, effectively setting the acceptance parameters to $beta = 0.96$

== Jumping
To enhance exploration beyond local minima, the algorithm supports three distinct jumping behaviors: no jumping, occasional jumping, and global jumping. Each mode serves a different purpose in escaping stagnation or revisiting over-explored regions.

=== No Jumping (-j)
By default, the algorithm operates without any forced jumps. After applying the standard acceptance criteria, the system proceeds to the next trial move using the configured displacement method (e.g., uniform random or MD). No additional mechanisms are triggered to forcibly escape the current local minimum unless the natural dynamics of the search lead to acceptance of a new state.

This mode is suitable for systems where local exploration is sufficient or when computational cost must be minimized. It also serves as the baseline against which the benefits of jumping strategies are evaluated.

=== Occasional Jumping (oj)
This strategy introduces an adaptive escape mechanism triggered by stagnation. If the algorithm accumulates a predefined number of consecutive rejected moves it initiates an occasional jump: a forced displacement out of the current local minimum, followed by a local optimization @Iwamatsu2004BasinHW.

Once the jump sequence completes and yields a new geometry, that configuration is automatically accepted, regardless of its energy, and the rejection counter is reset to zero. This prevents the system from becoming trapped in flat or high-barrier regions where standard moves repeatedly fail.

The displacement during the jump can be generated via either uniform random perturbations (as defined in Eq. 1) or molecular dynamics (MD), controlled by the chosen jump distribution parameter. In all simulations reported here, we use uniform distribution as the jump distribution.

Note: Occasional jumping operates after the acceptance decision. It does not interfere with the trial move phase and is compatible with Minima Hopping (MH) history, which tracks only accepted configurations.

=== Global Jumping (gj)
Global jumping provides a stronger, history-aware escape mechanism. Instead of counting rejections, it triggers a jump when the current local minimum has been visited more than a specified number times. This requires maintaining a full history of previously accepted geometries — effectively tracking how often each unique basin has been revisited.

Like occasional jumping, global jumping occurs after the standard acceptance criterion is evaluated. Crucially, global jumping is incompatible with MH history, because MH inherently prevents reacceptance of any previously stored minimum. Since global jumping relies on detecting repeated visits to the same geometry, it cannot function if that geometry is never allowed to be accepted again.

When activated, global jumping performs a large-scale displacement (again using a jump distribution) followed by local optimization. The resulting structure is automatically accepted, and the visit counter for that geometry is reset.

== System Description
We tested each mixture on a 100 random configurations of $LJ(38)$ and $LJ(55)$ and 200 random configurations of $LJ(75)$ and $LJ(102)$ to represent the spectrum of topological difficulty. Based on preliminary benchmarking and also seen by Wales in his experiments with Basin Hopping @Wales, these systems are categorized into two classes:
1. *Well Behaved Systems $N = 38, 55$*: The PES generally have nice properties where local minimization efficiently leads toward the global minimum.
  - $LJ(55)$: A single-funnel landscape dominated by the Mackay icosahedron. While the global minimum is not found by simple minimization, the funnel structure makes it the most easily accessible to either algorithm.
  - $LJ(38)$: An intermediate system containing a double-funnel structure (truncated octahedron vs. icosahedral isomers). However the algorithms are able to effectively find the global minima.
2. *Deceptive Systems $N = 75, 102$ *: These landscapes contain deep "pseudo-global" minima separated from the true global minimum by high energy barriers, creating traps that optimizers struggle to escape. In both cases there is a a icosahedral trap geometry that acts as a "deceptive" double funnel, preventing algorithms from finding the decahedral global minimum.

In our experiments we saw that if any of the algorithms entered what we called the "catchment" area of the icosahedral trap geometry for $LJ(75)$ and $LJ(102)$ they were almost never able to exit, this informed the computational protocol needed to test $LJ(75)$ and $LJ(102)$.

== Computational Protocols
Simulations were performed using a localized L-BFGS optimizer. Based on the failure modes observed in the deceptive systems, outcome classifications were defined as follows:

1. *Global Convergence (True Success)*: A run was classified as truly successful if the potential energy was within $0.01$ eV of the known global minimum.
2. *Pseudo-Global Convergence (Trap Success)*: A run was classified as a fake success (for $LJ(75)$ and $LJ(102)$ ) if the potential energy was within $0.01$ eV of the icosahedral local minimum.
3. *Failure*: A run failed if it exceeded $5 times 10^6$ local minimization steps or if numerical instability caused the force calculation to diverge.

== Statistical Analysis and Performance Metrics
To move beyond simple efficiency comparisons, we employed a multi-criteria evaluation framework designed to penalize "brittle" algorithms that sacrifice robustness for speed.

=== Aggregate Weighted Score

=== Pareto Efficiency (Efficiency Analysis)

=== Maximin Criterion (Robustness Analysis)
