#import "template.typ": *

#show: homework.with(
  course: "Algebra Qual Prep",
  assignment: "Group Theory Practice",
  name: "Arham Lodha",
  due: "",
)

// Skill-targeted practice problems for Group Theory. Each problem names its skill, tier,
// and related qual problems (by "Term Year #N"; see ../../qual/). No solutions are written here.
// Source for Set 1 and Set 2: Arham's own list (self-assigned, after Aluffi Ch. 2 proved too easy).

#let meta(tier, skill, related) = text(size: 0.85em, style: "italic")[
  Tier: #tier #h(0.5em)|#h(0.5em) Skill: #skill #h(0.5em)|#h(0.5em) Related quals: #related
]

= Set 1: Elementary Group Theory

#problem("Cube power map")[
  Suppose $(x y)^3 = x^3 y^3$ for all $x, y in G$, and $G$ has no elements of order $3$. Prove $G$ is abelian.

  #meta[★★][power maps / forcing commutativity][no close analogue; same flavor as Spring 2007 #3, Fall 2017 #2]
]
#proof[
  We will prove this result as a series of claims. The first claim is that $(y x)^2 = x^2 y^2$. $        (x y)^3 & = x^3 y^3 \
  => x y x y x y & = x^3 y^3 \
      => (y x)^2 & = x^2 y^2. $ Consider $p: G -> G$ where $x -> x^3$, the assumption about the group tells us that $p$ is a homomorphism furthermore the fact that no element has order 3, $p$ is injective. Suppose $ x^3 y^3 = y^3 x^3 => p(x y) = p(y x) => x y = y x. $ Thus if the cubes of two elements commute then the two elements themselves commute. Now we will prove that $ x^3 y^2 = y^2 x^3 $ for any pair $x$ and $y$. $ x^3 y^2 & = x x^2 y^2 \
          & = x y x y x \
          & = (x y)^2 x \
          & = y^2 x^2 x = y^2 x^3. $

  Now we will prove that everything commutes with squares. $ x^3 (y^2)^3 & = (y^2)^3 x^3 quad (x^3 y^2 = y^2 x^3 "repeatedly"). $

  Thus $x y^2 = y^2 x$. $ y x y x & = (y x)^2 \
          & = x^2 y^2 \
          & = y^2 x^2 \
      x y & = y x. $


]

#problem("Central quotient and the 5/8 theorem")[
  Prove that if $G\/Z(G)$ is cyclic, then $G$ is abelian. Then prove the "5/8 theorem": if $G$ is finite and nonabelian, the probability that two random elements commute is at most $5/8$.

  #meta[★ (first claim), ★★ (5/8)][centers, class equation / counting commuting pairs][Fall 2001 G1, Fall 2004 Problem 1, Spring 2001 A2, Fall 2011 Problem 2]
]
#proof[
  Suppose $lcoset(G, Z(G))$ is cyclic. Thus exists $g in G$ such that $lcoset(G, Z(G)) = chevron.l g Z(G) chevron.r$. Thus for all $a, b in G$, $a = g^k z_1$ and $b = g^m z_2$. Hence $ a b & = g^k z_1 g^m z_2 \
      & = g^m z_2 g^k z_1 \
      & = b a. $ Thus $G$ is abelian.
]

#problem("Unions of subgroups")[
  Prove that no group is a union of two proper subgroups. Find a group that is a union of three. For a challenge, characterize all such groups.

  #meta[★★ (challenge ★★★)][covering arguments, counting via quotients][Spring 2016 #9, Spring 2004 Problem 1]
]
#proof[
  Assume for the sake of contradiction, $G = H union K$ where $H, K$ are proper. Suppose $h in H - K$ and $k in K - H$. $h k in G$. We have various cases:
  1. $h k in H$: Then $h^(-1) h k = k in H$ which is a contradiction.
  2. $h k in K$: Then $h = h k k^(-1) in K$, which is a contradiction.
  Thus $h k in.not H union K = G$, thus a contradiction occurs.
]

#problem("Smallest prime index")[
  Let $p$ be the smallest prime dividing $|G|$. Prove that a subgroup of index $p$ is normal. (Hint: let $G$ act on the cosets.)

  #meta[★★][action on cosets, $G -> S_p$][Spring 2004 Problem 3, Fall 2014 #6, Winter 2005 A1, Fall 2006 G2]
]
#proof[

]

#problem("Finite subgroups of a field's units")[
  Prove that every finite subgroup of the multiplicative group of a field is cyclic. (Count elements of each order and compare with $sum_(d | n) phi(d) = n$.)

  #meta[★★][counting elements by order; $sum_(d | n) phi(d) = n$][Fall 2000 A3, Fall 2008 G2]
]

#problem([Generating $S_n$])[
  Prove $S_n$ is generated by $(1 med a)$ and $(1 med 2 med dots.c med n)$ if and only if $gcd(a-1, n) = 1$.

  #meta[★★][generators of $S_n$, transitivity plus transposition][Spring 2008 G1, Winter 2003 A3]
]

#problem([Generators of $SL_2(ZZ)$])[
  Prove $SL_2(ZZ)$ is generated by $mat(delim: "(", 0, -1; 1, 0)$ and $mat(delim: "(", 1, 1; 0, 1)$. (Hint: think of the Euclidean algorithm.)

  #meta[★★][Euclidean algorithm as row reduction][Spring 2006 G2, Fall 2006 G3, Spring 2020 #6 (finite-field $SL_2$, related setting)]
]

#problem("Subgroups of $QQ$")[
  Prove that every finitely generated subgroup of $QQ$ is cyclic, that $QQ$ has no maximal subgroups, and that $QQ\/ZZ$ has exactly one subgroup of each finite order.

  #meta[★★][divisible groups, f.g. torsion-free rank 1][Winter 2005 A2, Fall 2008 G3, Fall 2005 Sec.1, Spring 2009 G2]
]

#problem([$"Aut"(ZZ\/n)$ and groups of order 6])[
  Compute $"Aut"(ZZ\/n)$. Show $"Aut"(ZZ\/2 times ZZ\/2) tilde.equiv S_3$, and use this to classify the groups of order $6$ by hand.

  #meta[★][automorphism groups, semidirect products][Spring 2012 #10, Fall 2006 G1, Winter 2002 A2, Fall 2013 #1, Spring 2015 #8, Spring 2008 G2]
]

= Set 2: Category Theory and Groups

// These sit outside the qual chapters; the qual touches them lightly (Spring 2015 #1, #2; Spring 2011 #10),
// but they build the universal-property fluency those problems assume.

#problem("Epimorphisms in Grp")[
  Prove that epimorphisms in $bold("Grp")$ are surjective. By contrast, show that the inclusion $NN arrow.r.hook ZZ$ is an epimorphism in $bold("Mon")$.

  #meta[★★★][universal properties, constructing test maps out of $G$][Spring 2015 #1, Spring 2015 #2]
]

#problem("Free groups on finite sets")[
  Prove that if $F(A) tilde.equiv F(B)$ as groups, then $|A| = |B|$ for finite sets $A$ and $B$. (Hint: count homomorphisms to $ZZ\/2$.)

  #meta[★★][counting homomorphisms out of a free object][Fall 2016 #1, Spring 2017 #3, Winter 2005 A3]
]

#problem("Coproducts")[
  Show that $ZZ\/2 * ZZ\/2$ (the coproduct in $bold("Grp")$) is the infinite dihedral group. Then explain why the coproduct in $bold("Ab")$ is so different.

  #meta[★][free products, presentations][Spring 2015 #1, Fall 2016 #1, Spring 2020 #1]
]

#problem("Fibered products")[
  Describe fibered products in $bold("Set")$ and $bold("Grp")$, and show that the kernel of a homomorphism is one of them.

  #meta[★][limits as universal objects][Spring 2015 #2 (categorical flavor)]
]

#problem("Representable functors on groups")[
  Show that $"Hom"_(bold("Grp"))(ZZ, -)$ is naturally isomorphic to the forgetful functor. What represents the functor sending $G$ to its set of elements of order dividing $n$?

  #meta[★★][Yoneda, representability][Spring 2011 Problem 10]
]

#problem("Mono, epi, and isomorphism")[
  Find a category where a morphism is both mono and epi but not an isomorphism. Then prove that a morphism that is mono and split epi is an isomorphism.

  #meta[★][basic categorical morphism types][Spring 2011 Problem 10]
]

// Coverage gaps relative to the qual Group chapter (candidates for future sets):
// Sylow counting and non-simplicity (orders 108, 300, 616, 2000, 504, pqr); p-group actions and centers;
// semidirect products and classification (orders 8, pq, 231, 315); solvability;
// Burnside counting and transitive/doubly transitive actions; f.g. abelian groups via Smith normal form;
// finite-index subgroups of f.g. / free groups; Aut of D_{2n}, S_4, Q_8 embeddings.
